# Generated by Django 3.0.12 on 2021-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsFixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(null=True)),
                ('day', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('home', models.CharField(blank=True, max_length=250, null=True)),
                ('xg_h', models.FloatField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=250, null=True)),
                ('xg_a', models.FloatField(blank=True, null=True)),
                ('away', models.CharField(blank=True, max_length=250, null=True)),
                ('attendance', models.IntegerField(null=True)),
                ('venue', models.CharField(blank=True, max_length=250, null=True)),
                ('referee', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.CharField(blank=True, max_length=250, null=True)),
                ('players_used', models.IntegerField(null=True)),
                ('avg_age', models.FloatField(null=True)),
                ('possession', models.FloatField(null=True)),
                ('games', models.IntegerField(null=True)),
                ('games_starts', models.IntegerField(null=True)),
                ('minutes', models.IntegerField(null=True)),
                ('minutes_90', models.FloatField(null=True)),
                ('goals', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('goals_pens', models.IntegerField(null=True)),
                ('pens_made', models.IntegerField(null=True)),
                ('pens_att', models.IntegerField(null=True)),
                ('cards_yellow', models.IntegerField(null=True)),
                ('cards_red', models.IntegerField(null=True)),
                ('goals_per90', models.FloatField(null=True)),
                ('assists_per90', models.FloatField(null=True)),
                ('goals_assists_per90', models.FloatField(null=True)),
                ('goals_pens_per90', models.FloatField(null=True)),
                ('goals_assists_pens_per90', models.FloatField(null=True)),
                ('xg', models.FloatField(null=True)),
                ('npxg', models.FloatField(null=True)),
                ('xa', models.FloatField(null=True)),
                ('xa_per90', models.FloatField(null=True)),
                ('xg_xa_per90', models.FloatField(null=True)),
                ('npxg_per90', models.FloatField(null=True)),
                ('npxg_xa_per90', models.FloatField(null=True)),
            ],
        ),
    ]
