# Generated by Django 3.0.12 on 2021-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_resultsfixtures_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsfixtures',
            name='week',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
