# Generated by Django 3.0.12 on 2021-02-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20210217_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsfixtures',
            name='attendance',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
