# Generated by Django 3.0.12 on 2021-02-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20210217_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsfixtures',
            name='week',
        ),
    ]
