# Generated by Django 3.0.12 on 2021-02-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_remove_resultsfixtures_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsfixtures',
            name='week',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
