# Generated by Django 3.0.12 on 2021-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_resultsfixtures_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=250, null=True)),
                ('squads', models.CharField(blank=True, max_length=500, null=True)),
                ('points', models.IntegerField(null=True)),
            ],
        ),
    ]
